### PR TITLE
Added live-filtering of table data with jQuery

### PR DESCRIPTION
**Pull request by traveling-walker**
Submitting to address open issue #8

### CODE REVIEW

**Comment by brianwalborn** [comment]
Thank you for your contribution (this was one I worked on for a minute but struggled to find an elegant solution for)! A few things:
1. The filter is also displaying on each section of the Settings page (the different settings use the UI Kit table element). We should add a way to conditionally show the field. #64 adds a `content.html` template that's shared between all data pages, so I'm thinking we can incorporate the filter field into that template and show/hide it similar to how the refresh button is shown/hidden with `show_refresh`
2. Could you please add the `uk-input` and `uk-form-width-small` classes to the input field? This will the make the field uniform with the rest of the UI (https://getuikit.com/docs/form)

**Comment by traveling-walker** [comment]
For item one, would your preference be to define a new boolean "show_filter" to pass, or include the filter creation in the existing "show_refresh" conditional block?

**Comment by brianwalborn** [comment]
> For item one, would your preference be to define a new boolean "show_filter" to pass, or include the filter creation in the existing "show_refresh" conditional block?

I think a new boolean would be the best path to make them mutually exclusive. What do you think?

**Comment by traveling-walker** [comment]
Yeah, I agree. Working on implementing those changes

**Comment by traveling-walker** [comment]
That's complete. Instead of inserting the input field after page load, I've just defined it as an HTML element in that conditional block. That did slightly affect its placement on the SSM instance select page. If that needs to be changed, just let me know!

**Comment by brianwalborn** [comment]
I think if we just turn the `span` `<span class="uk-text-meta">Select the instances on which you'd like to run a command.</span>` into a `p`, it solves our problem.

**Comment by traveling-walker** [comment]
That's been addressed.

**Pull request merged**
